import Head from 'next/head'
import Header from '../components/Header';
import { ChakraProvider } from '@chakra-ui/react'

export default function Home() {
    return (
        <div className=''>
            <Head>
                <title>
                  Developer Nick
                </title>

                <meta name='description' content='Generated by create next app'/>
                <link rel='icon' href='/favicon.ico'/>
            </Head>

           <Header />
        </div>
    )
}
